disabled_rules: # rule identifiers to exclude from running
 - trailing_whitespace
excluded: # paths to ignore during linting. Takes precedence over included.
 - Carthage
 - Pods
line_length: 150
variable_name:
 min_length: # only min_length
   warning: 3 # only warning
 excluded: # excluded via string array
   - id
   - URL
nesting:
 type_level:
   warning: 2
large_tuple: # warn user when using 3 values in tuple, give error if there are 4
  - 3
  - 4
